server :
  port : 8000
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/enjoy?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  config-location: classpath:config/myBatis.xml

jwt:
  secret_key: SECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEY
  expTime : 86400000

  spring:
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLInnoDBDialect
          format_sql: 'true'
      database-platform: org.hibernate.dialect.MySQL5Dialect  #데이터플랫폼 지정
      hibernate:
        ddl-auto: update
      show-sql: 'false'

file: E:\miniPJT\posco_mini_back\back\src\main\resources\static