server :
  port : 8000
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/enjoy?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:

        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL5Dialect  #데이터플랫폼 지정
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false


mybatis:
  config-location: classpath:config/myBatis.xml

jwt:
  secret_key: SECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEY
  expTime : 86400000


  spring:
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLInnoDBDialect
          format_sql: 'true'
      database-platform: org.hibernate.dialect.MySQL5Dialect  #데이터플랫폼 지정
      hibernate:
        ddl-auto: update
      show-sql: 'false'

file: E:\Project_back\posco_mini_back\back\src\main\resources\static

app:
  firebase-configuration-file: C:\Users\geunyeong\Desktop\native-back\posco_mini_back\back\src\main\resources\keystore\google-services.json